In [1]:
from matplotlib import pyplot as plt
import numpy as np

In [12]:
# Bihn and Korn function without constraints

def f1(x):
    return 4*(x[:,0]**2 + x[:,1]**2)

def f2(x):
    return (x[:,0]-5)**2 + (x[:,1]-5)**2

In [22]:
def BruteForcePareto(functions, lb, ub, varNum = 10):
    pareto_front = []
    
    dim = len(lb)
    fNum = len(functions)

    # Initialzing function variables as random n-dimensional points with values between lower and upper bounds
    x = np.random.random((varNum, dim)) * (ub - lb) + lb
    print(x)
    print(x.shape)

    # Calculating function values of said variables
    y = np.empty((varNum, fNum))
    for i in range(fNum):
        y[:, i] = np.array(functions[i](x))
    print(y)
    print(y.shape)

In [23]:
BruteForcePareto(functions=[f1, f2], lb=np.array([0, 0]), ub=np.array([3, 5]), varNum=5)

[[0.69145731 2.52946478]
 [0.49908987 4.17697097]
 [2.11938272 3.94059521]
 [0.47487552 0.03524795]
 [2.9027896  3.08500813]]
(5, 2)
[[27.50522123 24.66708435]
 [70.7847087  20.93556882]
 [80.08029499  9.4202944 ]
 [ 0.9069967  45.12551455]
 [71.77385052  8.06548532]]
(5, 2)


In [17]:
f1(np.array([[0.41824066,3.16200161]]))

array([40.69271773])